- pom.xml
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/LimitedPartnershipsApiApplication.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/LimitedPartnershipsController.java
https://companieshouse.atlassian.net/browse/LP-111
Mavenized the project
Then manually added spring boot modules to POM:
- spring-boot-starter-web
- spring-boot-starter-actuator
- spring-boot-starter-test
based on ROE but with the the most up to date version.
Manually added the plugin.
Then added also manually:
- the main app class
- a controller containing the health check
> LP-111 create a basic spring boot api

- pom.xml
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/LimitedPartnershipsApiApplication.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/utils/ApiLogger.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/utils/ApiLoggerTest.java
JIRA: https://companieshouse.atlassian.net/browse/LP-116
Add structured logging along with the unit tests.
> LP-116 Add structured logging

- .gitignore
- Makefile
- pom.xml
https://companieshouse.atlassian.net/browse/LP-171
Add Makefile
Update .gitignore to ignore the target folder that is used as the build output folder, and ignore intellij config files
> LP-171 Add Makefile and update .gitignore

- pom.xml
https://companieshouse.atlassian.net/browse/LP-173
Add sonar config to POM
> LP-173 Add sonar config to POM

- suppress.xml
Pipeline security task needs a suppress.xml file
> Add suppress.xml file for security pipeline job

- terraform/groups/ecs-service/data.tf
- terraform/groups/ecs-service/main.tf
> add lb listener and correct app version var

- .github/PULL_REQUEST-TEMPLATE.md
https://companieshouse.atlassian.net/browse/LP-169
create a PR template for limited-partnership-api
> create a PR template for limited-partnership-api

- terraform/groups/ecs-service/main.tf
- terraform/groups/ecs-service/variables.tf
correct multi lb config
* [ x ] Infrastructure change
> add multi lb config

- .github/dependabot.yml
https://companieshouse.atlassian.net/browse/LP-168
Add dependabot config to limited-partnerships-api
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` …
> Add dependabot config to limited-partnerships-api

- terraform/groups/ecs-service/main.tf
setting ReadOnlyFileSytem to false
and added depends on module as it is missing.
* [ x ] Infrastructure change
```
``` …
> set readOnlyFileSystem to false

- .github/PULL_REQUEST-TEMPLATE.md
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE …
> amend text remove duplication of tests text

- README.md
https://companieshouse.atlassian.net/browse/LP-209
Update the README
Add endpoint information
Add Terraform info
```
``` …
> LP-209 Update the README.md file

- pom.xml
- spec/schema.json
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/PartnershipController.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/dto/LimitedPartnershipSubmissionCreatedResponseDto.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/utils/Constants.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/PartnershipControllerTest.java
https://companieshouse.atlassian.net/browse/LP-206
First part of the https://companieshouse.atlassian.net/browse/LP-206 work
Create an initial post endpoint
There is no body yet or header info
```
```
- feat: a commit that introduces a new feature to the codebase (this correlates with …
> LP-206 create initial version of post endpoint

- pom.xml
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/LimitedPartnershipsApiApplication.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/mapper/LimitedPartnershipMapper.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/PartnershipNameEnding.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/dao/DataDao.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/dao/LimitedPartnershipSubmissionDao.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/dto/DataDto.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/dto/LimitedPartnershipSubmissionDto.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/repository/LimitedPartnershipSubmissionsRepository.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnershipService.java
- src/main/resources/application.properties
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/mapper/LimitedPartnerMapperTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnershipServiceTest.java
https://companieshouse.atlassian.net/browse/LP-207
1. Added service with method to create submission data in Mongo
2. Added mapStruct mapper to convert DTO object in to DAO object. 
```
```
- feat: a commit that introduces a new feature to the codebase (this correlates with MINOR in …
> LP-207 create service to persist submission

- terraform/groups/ecs-service/main.tf
update tf modules, mount points included at module level and defaults set to true. Removed mount point and volume from code
* [ x ] Infrastructure change
```
```
- BREAKING …
> update- tf modules and remove tmp mount

- pom.xml
https://companieshouse.atlassian.net/browse/LP-214
Based on this post: https://stackoverflow.com/questions/76706612/standard-commons-logging-discovery-in-action-with-spring-jcl
There is a transitive dependency on commons-logging Spring find this and warns of potential conflicts. The transitive dependency is on api-security-java and the post recommends and exclude node to be adde dint he mvn pom.
```
```
and contain the following …
> lp-214 Handle logging depencency conflict

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/PartnershipController.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/exception/ServiceException.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnershipService.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/TransactionService.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/utils/Constants.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/PartnershipControllerTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnershipServiceTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/TransactionServiceTest.java
https://companieshouse.atlassian.net/browse/LP-225
* LP service changes to receive a transaction and update it with name and links
* A new Transaction service to perform updates
* Unit tests for the new and changed functionality
```
```
- feat: a commit that introduces a new feature to …
> LP-225 Update transaction with LP details

- pom.xml
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/PartnershipController.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/exception/GlobalExceptionHandler.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/PartnershipControllerTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/exception/GlobalExceptionHandlerTest.java
https://companieshouse.atlassian.net/browse/LP-280
* Added a global exception handler to ensure that all uncaught exceptions are logged with a stack trace
* Log output encoded and truncated
* Unit test added
```
```
- feat: a commit that introduces a new feature to the codebase (this …
> LP-280 Add Global Exception Handler

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/PartnershipNameEnding.java
https://companieshouse.atlassian.net/browse/LP-217
fix name ending enum
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API …
> lp-217 : fix name ending enum

- terraform/groups/ecs-service/locals.tf
https://companieshouse.atlassian.net/browse/LP-197
* Should fix the issue in CiDev and other test envs
```
``` …
> LP-197 Change LB path for API calls

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/dto/LimitedPartnershipSubmissionCreatedResponseDto.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/mapper/LimitedPartnerMapperTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnershipServiceTest.java
N/A
Fix some minor sonar code smells
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in …
> Fix some minor sonar code smells

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/dto/DataDto.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/mapper/LimitedPartnerMapperTest.java
https://companieshouse.atlassian.net/browse/LP-304
get endpoint return limited partnership with name_ending description
```
``` …
> lp-304 : get limited partnership - name_ending description

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/LimitedPartnershipsApiApplication.java
trigger new pipeline build
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic …
> remove blankspace

- pom.xml
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/PartnershipController.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/exception/GlobalExceptionHandler.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/dto/DataDto.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/dto/LimitedPartnershipSubmissionDto.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/dto/validator/NameSize.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/dto/validator/NameSizeValidator.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/PartnershipControllerTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/PartnershipControllerValidationTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/model/LimitedPartnershipSubmissionDtoValidationTest.java
https://companieshouse.atlassian.net/browse/LP-373
add dto validation on post request
```
``` …
> lp-373 : dto validation on post endpoint

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/IncorporationController.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/dao/IncorporationDataDao.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/dao/LimitedPartnershipIncorporationDao.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/repository/LimitedPartnershipIncorporationRepository.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnershipIncorporationService.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/utils/Constants.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/IncorporationControllerTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnershipIncorporationServiceTest.java
https://companieshouse.atlassian.net/browse/LP-415
New endpoint for creating incorporation type record:
POST /transactions/{transaction_id}/incorporation/limited-partnership
```
```
- feat: a commit that introduces a new feature to the codebase (this correlates with MINOR in semantic …
> LP-415 Implement Incorporation POST endpoint

- spec/schema.json
https://companieshouse.atlassian.net/browse/LP-422
Update the schema spec to add the incorporation GET and POST endpoints
and add the partnership GET endpoint
```
```
- …
> LP-422 Update spec with GET POST incorporations

- pom.xml
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/IncorporationController.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/dao/IncorporationDataDao.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/dao/LimitedPartnershipIncorporationDao.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnershipIncorporationService.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/utils/Constants.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/IncorporationControllerTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnershipIncorporationServiceTest.java
https://companieshouse.atlassian.net/browse/LP-415
- Update the transaction with incorporation resource. Note, the filing_mode cannot be set yet as it require changes to the java SDK.
- Generate and persist etag.
- Introduced Builder pattern to instantiate DAO.
```
```
- feat: a commit …
> LP_415 Update transaction with incorporation details and create etag

- pom.xml
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnershipIncorporationService.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnershipIncorporationServiceTest.java
https://companieshouse.atlassian.net/browse/LP-445
add filing_mode to transaction
```
``` …
> lp-445 : add filing_mode to transaction

- terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars
Removing duplicate desired_task_count from the live vars
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change …
> Removing duplicate desired_task_count

- spec/schema.json
https://companieshouse.atlassian.net/browse/LP-465
Update api spec to include POST endpoint for limited partner
Added new tags to group endpoints.
```
```
- BREAKING CHANGE: …
> LP-465 Add POST Limited Partner to spec

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/config/InterceptorConfig.java
- terraform/groups/ecs-service/locals.tf
https://companieshouse.atlassian.net/browse/LP-415
Update interceptor config and listener for incorporation endpoints
```
``` …
> LP-415 - Update interceptor config and listener for incorporation endpoints

- spec/schema.json
https://companieshouse.atlassian.net/browse/LP-525
Add General Partner POST, PUT and PATCH to spec
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` …
> LP-525 Add General Partner endpoint to API spec

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/LimitedPartnerController.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/repository/LimitedPartnerRepository.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnerService.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/utils/TransactionUtils.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/LimitedPartnerControllerTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnerServiceTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/utils/TransactionUtilsTest.java
https://companieshouse.atlassian.net/browse/LP-508
API - Implement GET endpoint for Limited Partner
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` …
> Create GET endpoint for limited-partner

- spec/schema.json
https://companieshouse.atlassian.net/browse/LP-592
Update incorporation endpoint to include "kind" in the POST request body to identify which type of journey (currently transition or registration).
```
```
- feat: a commit that introduces a new feature to the codebase (this correlates …
> LP-592 Update incorporation endpoint for Transition journey

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/GeneralPartnerController.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/GeneralPartnerService.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnerService.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/utils/TransactionUtils.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/GeneralPartnerControllerTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/GeneralPartnerServiceTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnerServiceTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/utils/TransactionUtilsTest.java
https://companieshouse.atlassian.net/browse/LP-587
- Retrieve general partner from mongo 
- Check the self link against the transaction
Unit tested controller, service, transaction link
```
```
- feat: a commit that introduces a new feature to the codebase (this correlates with MINOR in …
> LP-587 Implement GET endpoint for General Partner

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/dto/GeneralPartnerDataDto.java
https://companieshouse.atlassian.net/browse/LP-587
Added json format to date of birth
Also added this to date effective from and the resignation date
```
```
- BREAKING …
> Lp 587 json date format fix

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/generalpartner/dto/GeneralPartnerDataDto.java
https://companieshouse.atlassian.net/browse/LP-595
GeneralPartnerDataDto - formerNames remove minimum size
```
``` …
> lp-595 : GeneralPartnerDataDto - formerNames remove minimum size

- pom.xml
N/A
Upgrade spring-boot to 3.4.3 to resolve security vulnerabilities reported in the pipeline dependency-check job.
```
``` …
> Upgrade spring-boot to resolve security vulnerabilities

- spec/schema.json
https://companieshouse.atlassian.net/browse/LP-644
Two new endpoints added:
- GET: /transactions/{transaction_id}/limited-partnership/general-partners
- GET: /transactions/{transaction_id}/limited-partnership/limited-partners
Updates to Incorporation GET endpoint to return lists of general and limited partners.
```
```
- fix: a commit that patches a bug in your codebase (this correlates with …
> LP-644 Update spec for GET list of General and Limited Partner endpoints

- spec/schema.json
https://companieshouse.atlassian.net/browse/LP-665
Add filings and validation status endpoints for:
- incorporations (filings endpoint only),
- partnerships,
- general partners,-
- limited partners
Tidy up - replaced:
- `Limited Partnership` with `Partnership`
- `submission_id` with `filing_resource_id` (as per the LP Service Design doc)
```
```
- fix: a commit that patches a bug in your …
> LP-655 Add filings and validation status endpoints

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/utils/Constants.java
https://companieshouse.atlassian.net/browse/LP-690
Fix the resume url used to resume a registration journey
```
``` …
> LP-690 Fix the resume url

- spec/schema.json
https://companieshouse.atlassian.net/browse/LP-657
Update fillings endpoints to return an array of filings to be consistent with other services.
```
```
- BREAKING CHANGE: a …
> LP-657 Fix filings endpoints in json schema

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/GeneralPartnerValidator.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/GeneralPartnerServiceValidateTest.java
https://companieshouse.atlassian.net/browse/LP-661
* No service address is being saved yet for a General Partner Person
* Validation check commented out with a TODO comment to re-include later
* Test assertions also commented out
```
```
- feat: a commit that introduces a new feature to …
> LP-661 Suppress running the GP Service Address validation check

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/validator/EnumValidator.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/GeneralPartnerValidator.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnershipIncorporationService.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnershipService.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnershipValidator.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/GeneralPartnerControllerUpdateTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/GeneralPartnerControllerValidationTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/IncorporationControllerValidationTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/PartnershipControllerTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/PartnershipControllerValidationTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/mapper/LimitedPartnerMapperTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/mapper/LimitedPartnershipMapperTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/GeneralPartnerServiceTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/GeneralPartnerServiceUpdateTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/GeneralPartnerServiceValidateTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnerServiceTest.java
N/A
Fix some Sonar code smells and warnings
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR …
> Fix some sonar code smells and IntelliJ warnings

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/partnership/dto/LimitedPartnershipCreatedResponseDto.java
N/A
Sonar - fix a smell where the JsonProperty mapping isn't needed as it is the same name as the field.
This is now similar to the other CreatedResponseDTOs
```
```
- …
> Sonar - Remove unused import and json property mapping

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/GeneralPartnerController.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/GeneralPartnerService.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/GeneralPartnerControllerTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/GeneralPartnerServiceTest.java
https://companieshouse.atlassian.net/browse/LP-649
Add new endpoint to get list of general partners for a given transaction id
```
```
- BREAKING CHANGE: a commit that has a …
> LP-649 Add getPartners list endpoint

- README.md
- pom.xml
https://companieshouse.atlassian.net/browse/ASM-480
Enable pull request analysis on new version of SonarQube:
https://sonarqube.companieshouse.gov.uk/dashboard?id=uk.gov.companieshouse%3Alimited-partnerships-api
```
```
- feat: a commit that introduces a new feature to the codebase (this …
> ASM-480 - Update SonarQube config for new version

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/limitedpartner/dao/LimitedPartnerDataDao.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/limitedpartner/dto/LimitedPartnerDataDto.java
https://companieshouse.atlassian.net/browse/LP-789
* Add the missing DAO and DTO fields for a Limited Partner Legal Entity
```
```
- BREAKING CHANGE: a commit that has a …
> LP-789 Ensure LP Legal Entity statement check saved to Mongo

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/GeneralPartnerController.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/LimitedPartnerController.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/PartnershipController.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/GeneralPartnerService.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/GeneralPartnerValidator.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnerService.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnerValidator.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnershipValidator.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/PartnerValidator.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/GeneralPartnerControllerValidationTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/LimitedPartnerControllerValidationTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnerServiceValidateTest.java
https://companieshouse.atlassian.net/browse/LP-717
* 'validation_status' resource link now added to transaction
* New controller endpoint added
* Java Bean validation applied by service
* Hard-coded mandatory field error checks also added for addresses
* Unit-tests added
```
```
- feat: a …
> LP-717 Add 'validation-status' endpoint and link for Limited Partner

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/FilingsService.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/utils/Constants.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/FilingsServiceTest.java
https://companieshouse.atlassian.net/browse/LP-244
Added function to set description on filing
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` …
> LP-244 function to add description to filing

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/IncorporationController.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/CostsService.java
- src/main/resources/application.properties
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/IncorporationControllerUpdateTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/IncorporationControllerValidationTest.java
- src/test/resources/application.properties
https://companieshouse.atlassian.net/browse/LP-749
add costs endpoint
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API …
> lp-749 : add costs endpoint

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/GeneralPartnerController.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/LimitedPartnerController.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/PartnershipController.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/CostsService.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/GeneralPartnerService.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnerService.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnershipService.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/GeneralPartnerControllerUpdateTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/GeneralPartnerControllerValidationTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/LimitedPartnerControllerUpdateTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/LimitedPartnerControllerValidationTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/PartnershipControllerUpdateTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/PartnershipControllerValidationTest.java
https://companieshouse.atlassian.net/browse/LP-749
add costs endpoint on each resource
```
``` …
> lp-749 : add costs endpoint on each resource

- pom.xml
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/FilingsController.java
N/A
fix the following warning that appears in the pipeline logs for the analyse PR job
[INFO] 11:54:09.726 'sonar.coverage.jacoco.xmlReportPaths' is not defined. Using default locations: target/site/jacoco/jacoco.xml,target/site/jacoco-it/jacoco.xml,build/reports/jacoco/test/jacocoTestReport.xml
```
```
- fix: a commit that patches a bug in your codebase (this correlates with PATCH in …
> Fix jacoco warning message on pipeline analyse job

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/CostsService.java
https://companieshouse.atlassian.net/browse/LP-752
Update the name of the product type for registration
The product type on the Cost endpoint is used by the payment-reconciliation-consumer and it will use this product type value to look up the product code from this file https://github.com/companieshouse/payment-reconciliation-consumer/blob/master/assets/product_code.yml
This change is just to bring the name in line with the other product names.
```
<type>[optional scope]: …
```
> LP-752 Update name of product type for registration

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnershipValidator.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnershipServiceValidateTest.java
https://companieshouse.atlassian.net/browse/LP-827
* Correct validation now also applied for LP and SLP partnerships
* Missing check on SIC codes added for PFLP and SPFLP partnerships
* Tests added and improved to cover all partnership types
```
```
- feat: a commit that introduces a new …
> LP-827 Validation status end-point changes for partnerships

- spec/schema.json
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/PartnershipController.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/partnership/dao/DataDao.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/partnership/dto/DataDto.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/partnership/dto/LimitedPartnershipPatchDto.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnershipValidator.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/mapper/LimitedPartnershipMapperTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/mapper/LimitedPartnershipPatchMapperTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnershipServiceUpdateTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnershipServiceValidateTest.java
https://companieshouse.atlassian.net/browse/LP-783
Add lawful purpose statement to limited partnership
```
``` …
> LP-783 Store lawful purpose statement on limited partnership

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/IncorporationController.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/TransactionService.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnershipServiceUpdateTest.java
N/A
Fix some more sonar issues
https://sonarqube.companieshouse.gov.uk/project/issues?issueStatuses=OPEN%2CCONFIRMED&impactSoftwareQualities=MAINTAINABILITY&branch=main&id=uk.gov.companieshouse%3Alimited-partnerships-api
```
```
- feat: a commit that introduces a new feature to the …
> Fix Sonar issues

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/PartnerValidator.java
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE …
> Not null refactor

- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/builder/TransactionBuilder.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/GeneralPartnerControllerUpdateTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/GeneralPartnerControllerValidationTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/IncorporationControllerUpdateTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/IncorporationControllerValidationTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/LimitedPartnerControllerUpdateTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/LimitedPartnerControllerValidationTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/PartnershipControllerUpdateTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/PartnershipControllerValidationTest.java
N/A
refactor - tests using TransactionBuilder
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with …
> refactor - tests using TransactionBuilder

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/common/dto/PartnerDto.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/generalpartner/dto/GeneralPartnerDto.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/limitedpartner/dto/LimitedPartnerDto.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/GeneralPartnerService.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/GeneralPartnerValidator.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnerService.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnerValidator.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/PartnerValidator.java
N/A
refactor partner validator
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic …
> refactor - partner validator

- spec/schema.json
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/config/InterceptorConfig.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/config/InterceptorConfigTest.java
https://companieshouse.atlassian.net/browse/LP-808
* End-points now only accessible by internal users (using an API key)
* Unit test updated
* Spec updated with 403 Forbidden codes
```
```
- feat: a commit that introduces a new feature to the codebase (this correlates with MINOR in …
> LP-808 Secure Filings and Costs end-points

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/FilingsController.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/FilingsService.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/FilingsControllerTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/FilingsServiceTest.java
https://companieshouse.atlassian.net/browse/LP-833
* Filing submission id now used to check that incorporation belongs to the supplied transaction
* Unit tests amended and added
* Miscellaneous tidy-ups in the filings code
```
```
- feat: a commit that introduces a new feature to the …
> LP-833 Check ids provided for a filings request

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/validator/UkPostcodeValidator.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/GeneralPartnerControllerUpdateTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/PartnershipControllerValidationTest.java
https://companieshouse.atlassian.net/browse/LP-894
add uk not mainland validation
```
``` …
> lp-874 : add uk not mainland validation

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/utils/Constants.java
https://companieshouse.atlassian.net/browse/LP-857
change the resume url to be generic
```
``` …
> LP-857 Change the resume url

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/limitedpartner/ContributionSubTypes.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/limitedpartner/dto/LimitedPartnerDataDto.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/validator/EnumValidator.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnerValidator.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/builder/LimitedPartnerBuilder.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/LimitedPartnerControllerUpdateTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/LimitedPartnerControllerValidationTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnerServiceValidateTest.java
N/A
validations
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A …
> Lp 778 capital contribution subtypes validation

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnerValidator.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/LimitedPartnerControllerUpdateTest.java
https://companieshouse.atlassian.net/browse/LP-653
fix null pointer for PFLP and SPFLP
```
``` …
> lp-653 : fix null pointer for PFLP and SPFLP

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/CompanyService.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/GeneralPartnerService.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/GeneralPartnerValidator.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnershipService.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/builder/CompanyBuilder.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/builder/TransactionBuilder.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/GeneralPartnerControllerUpdateTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/GeneralPartnerControllerValidationTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/CompanyServiceTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/GeneralPartnerServiceCreateTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/GeneralPartnerServiceValidateTest.java
https://companieshouse.atlassian.net/browse/LP-942
add dateEffectiveFrom validation for transition journey
```
``` …
> lp-942 : add dateEffectiveFrom validation for transition journey

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/limitedpartner/dto/LimitedPartnerDataDto.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnerValidator.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/LimitedPartnerControllerUpdateTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnerServiceValidateTest.java
https://companieshouse.atlassian.net/browse/LP-972
- Removed regex validation for capital contribution value.
- Introduced validation using conversion to a BigDecimal type.
- Changed unit tests as we are validating in a different part of the code.
```
```
- feat: a commit that introduces …
> LP-972 Validation improvement capital contribution values

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnershipService.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/TransactionService.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnershipServiceTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/TransactionServiceTest.java
https://companieshouse.atlassian.net/browse/LP-468
- Moved these methods: 
- updateTransactionWithLinksAndPartnershipName 
- hasExistingLimitedPartnership
- createLimitedPartnershipTransactionResource
Updated partnership service tests and moved two tests to the transaction service tests.
```
```
- fix: a commit that patches a bug in your codebase (this correlates with PATCH in semantic …
> LP-468 Move methods from partnerships to the transaction service

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/common/PartnerKind.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/common/dto/PartnerDataDto.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/incorporation/IncorporationKind.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/GeneralPartnerService.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/builder/GeneralPartnerBuilder.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/GeneralPartnerServiceContainerTest.java
https://companieshouse.atlassian.net/browse/LP-949
add partner kind
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change …
> lp-949 : add partner kind

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/GeneralPartnerValidator.java
https://companieshouse.atlassian.net/browse/LP-948
update validatePartial method in GeneralPartnerValidator to only check for not disqualified statement checked on REGISTRATION incorporation kind
```
```
- feat: a commit that introduces a new feature to the codebase (this correlates with …
> LP-948 add general partner person (pt)

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/FilingsService.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/FilingsServiceTest.java
https://companieshouse.atlassian.net/browse/LP-899
* Description was previously hard-code for registration
* Journey type now checked and correct description set
* Unit test added
```
```
- feat: a commit that introduces a new feature to the codebase (this correlates with MINOR in …
> LP-899 Set correct filing description for transition submissions

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/GeneralPartnerValidator.java
https://companieshouse.atlassian.net/browse/LP-948
Amend validatePartial general partner method to check for not disqualified statement on post transition as well.
```
```
- …
> LP-948 amend validatePartial method check

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnerService.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/TransactionService.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/builder/LimitedPartnerBuilder.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnerServiceCreateTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnerServiceTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnerServiceUpdateTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnerServiceValidateTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/TransactionServiceTest.java
https://companieshouse.atlassian.net/browse/LP-1102
fix create LP - post-transition
- set kind
- transaction check
```
``` …
> lp-1102 : fix create LP - post-transition

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/config/InterceptorConfig.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/FilingsController.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/FilingsService.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/FilingsControllerTest.java
https://companieshouse.atlassian.net/browse/LP-1105
add LP filing endpoint
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API …
> lp-1105 : add LP filing endpoint

- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/builder/GeneralPartnerBuilder.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/builder/LimitedPartnerBuilder.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/builder/LimitedPartnershipBuilder.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/builder/TransactionBuilder.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/GeneralPartnerControllerTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/IncorporationControllerTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/LimitedPartnerControllerTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/PartnershipControllerTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/model/LimitedPartnershipDtoValidationTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/repository/GeneralPartnerRepositoryTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/FilingsServiceTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/GeneralPartnerServiceUpdateTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/GeneralPartnerServiceValidateTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnerServiceTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnerServiceUpdateTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnershipIncorporationServiceTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnershipServiceTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnershipServiceUpdateTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/TransactionServiceTest.java
N/A
refactor : tests - use builders
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in …
> refactor : tests - use builders

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/GeneralPartnerService.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnerService.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnershipService.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/builder/GeneralPartnerBuilder.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/builder/LimitedPartnerBuilder.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/builder/LimitedPartnershipBuilder.java
N/A
fix - default kind non post-transition journey
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating …
> fix : default kind non post-transition journey

- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/PartnershipControllerValidationTest.java
https://companieshouse.atlassian.net/browse/LP-1065
Fix pipeline test failure - PartnershipControllerValidationTest
```
``` …
> LP-1065 Fix PartnershipControllerValidationTest

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/PartnershipController.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnershipService.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/validator/LimitedPartnershipValidator.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/IncorporationControllerUpdateTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/PartnershipControllerTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/PartnershipControllerUpdateTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/controller/PartnershipControllerValidationTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnershipServiceTest.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnershipServiceUpdateTest.java
https://companieshouse.atlassian.net/browse/LP-1090
add date of update validation - date of update after date of incorporation
```
```
- BREAKING CHANGE: a commit that has a …
> lp-1090 : add date of update validation

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/validator/posttransition/PostTransitionStrategyHandler.java
https://companieshouse.atlassian.net/browse/LP-1122
update Cost object to satisfy payment-api service expectation
```
``` …
> lp-1122 : update Cost object to satisfy payment-api service expectation

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/GeneralPartnerService.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnerService.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnershipService.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/validator/posttransition/PostTransitionStrategyHandler.java
N/A
replace ternary by MoreObjects.firstNonNull
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with …
> refactor : replace ternary by MoreObjects.firstNonNull

- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/model/partnership/PartnershipType.java
- src/main/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnerService.java
- src/test/java/uk/gov/companieshouse/limitedpartnershipsapi/service/LimitedPartnerServiceCreateTest.java
N/A
fix : add limited partner in post transition
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with …
> fix : add limited partner in post transition
